// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppStats() {
  return window['go']['main']['App']['GetAppStats']();
}

export function GetSkillTree() {
  return window['go']['main']['App']['GetSkillTree']();
}

export function GetTodaySummary() {
  return window['go']['main']['App']['GetTodaySummary']();
}

export function GetTrends(arg1) {
  return window['go']['main']['App']['GetTrends'](arg1);
}
