// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildSessionsForDate(arg1:string):Promise<main.SessionBuildResultDTO>;

export function RebuildSessionsForDate(arg1:string):Promise<main.SessionBuildResultDTO>;

export function EnrichSessionsForDate(arg1:string):Promise<main.SessionEnrichResultDTO>;

export function GetAppStats():Promise<Array<main.AppStatsDTO>>;

export function GetDailySummary(arg1:string):Promise<main.DailySummaryDTO>;

export function GetDiffDetail(arg1:number):Promise<main.DiffDetailDTO>;

export function GetPeriodSummary(arg1:string,arg2:string):Promise<main.PeriodSummaryDTO>;

export function GetSessionDetail(arg1:number):Promise<main.SessionDetailDTO>;

export function GetSessionsByDate(arg1:string):Promise<Array<main.SessionDTO>>;

export function GetSettings():Promise<main.SettingsDTO>;

export function GetSkillEvidence(arg1:string):Promise<Array<main.SkillEvidenceDTO>>;

export function GetSkillSessions(arg1:string):Promise<Array<main.SessionDTO>>;

export function GetSkillTree():Promise<Array<main.SkillNodeDTO>>;

export function GetTodaySummary():Promise<main.DailySummaryDTO>;

export function GetTrends(arg1:number):Promise<main.TrendReportDTO>;

export function ListPeriodSummaryIndex(arg1:string,arg2:number):Promise<Array<main.PeriodSummaryIndexDTO>>;

export function ListSummaryIndex(arg1:number):Promise<Array<main.SummaryIndexDTO>>;

export function SaveSettings(arg1:main.SaveSettingsRequestDTO):Promise<void>;
