// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppStats() {
  return window['go']['main']['App']['GetAppStats']();
}

export function GetDailySummary(arg1) {
  return window['go']['main']['App']['GetDailySummary'](arg1);
}

export function GetDiffDetail(arg1) {
  return window['go']['main']['App']['GetDiffDetail'](arg1);
}

export function GetSkillEvidence(arg1) {
  return window['go']['main']['App']['GetSkillEvidence'](arg1);
}

export function GetSkillTree() {
  return window['go']['main']['App']['GetSkillTree']();
}

export function GetTodaySummary() {
  return window['go']['main']['App']['GetTodaySummary']();
}

export function GetTrends(arg1) {
  return window['go']['main']['App']['GetTrends'](arg1);
}

export function ListSummaryIndex(arg1) {
  return window['go']['main']['App']['ListSummaryIndex'](arg1);
}
